### ISSUE TITLE
Error when downloading model

### ISSUE THREAD

**Issue by xjyribro** [DenisovAV/flutter_gemma#35]
I followed the example and used this code. Model is hosted on GDrive

```
if (!isLoaded) {
      await for (int progress in FlutterGemmaPlugin.instance.loadNetworkModelWithProgress(url: 'https://drive.google.com/file/d/XXXX/view?usp=drive_link')) { 
        setState(() {
          _loadingProgress = progress;
        });
      }
    }
```

I get this error:
```E/mple.gemma_tes(27063): open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found```

**Comment by xjyribro** [comment]
My pubspec:

```
dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_gemma: ^0.4.2
  cupertino_icons: ^1.0.6
  flutter_markdown: ^0.7.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gemma.png
    - assets/background.png
```
